# NAME: GitHub
# AUTHOR: blackmatrix7
# REPO: https://github.com/blackmatrix7/ios_rule_script
# UPDATED: 2024-07-03 16:14:51
# DOMAIN-KEYWORD: 1
# DOMAIN-SUFFIX: 29
# TOTAL: 30
- DOMAIN-SUFFIX,weixin.qq.com,DIRECT
- DOMAIN-SUFFIX,qq.com,DIRECT
- DOMAIN-SUFFIX,wechat.com,DIRECT
- DOMAIN-SUFFIX,tencent.com,DIRECT
- IP-CIDR,42.192.0.0/24,DIRECT
- IP-CIDR,119.29.0.0/16,DIRECT
- IP-CIDR,129.226.0.0/16,DIRECT
- IP-CIDR,175.24.0.0/16,DIRECT
