# NAME: GitHub
# AUTHOR: chang0438
# REPO: https://github.com/blackmatrix7/ios_rule_script
# UPDATED: 2026-04-026 16:14:51
# DOMAIN-KEYWORD: 1
# DOMAIN-SUFFIX: 29
# TOTAL: 30
- DOMAIN-SUFFIX,weixin.qq.com
- DOMAIN-SUFFIX,weixin.qq.hk
- DOMAIN-SUFFIX,qq.com
- DOMAIN-SUFFIX,qq.com.hk
- DOMAIN-SUFFIX,wechat.com
- DOMAIN-SUFFIX,tencent.com
- IP-CIDR,42.192.0.0/24
- IP-CIDR,119.29.0.0/16
- IP-CIDR,129.226.0.0/16
- IP-CIDR,175.24.0.0/16
